config/routes.rb
Rails.application.routes.draw do
  resources :togs

  root 'togs#follows'

  get 'oauth/connect' => 'oauth#connect'
  get 'oauth/callback' => 'oauth#callback'

  resources :togs do
    collection do
      get 'follows'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/oauth_controller.rb
require "instagram"

class OauthController < ApplicationController
  def connect
  	redirect_to Instagram.authorize_url(:redirect_uri => ::CALLBACK_URL)
  end

  def callback
  	response = Instagram.get_access_token(params[:code], :redirect_uri => ::CALLBACK_URL)
  	session[:access_token] = response.access_token
    p follows_togs_path
    p '%%%%%%%%%%%%%%%%%%%%'
  	redirect_to :controller => 'togs', :action => 'index'
  end
end

app/controllers/togs_controller.rb
class TogsController < ApplicationController
      
    def index
      client = Instagram.client(:access_token => session[:access_token])
      @user = client.user
      @follows = client.user_follows('self', :count => 30)

      @hash = Gmaps4rails.build_markers(@follows) do |user, marker|
        begin
          media = Instagram.user_recent_media(user.id)

            if media.first.location
                marker.lat media.first.location.latitude
                marker.lng media.first.location.longitude
            end

          p user.id
          p media.first.location

        rescue Exception => e
          puts e
        end
      end.reject!(&:empty?)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/togs_helper.rb
module TogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instabrief</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/oauth/callback.html.erb
<h1>Oauth#callback</h1>
<p>Find me in app/views/oauth/callback.html.erb</p>

app/views/oauth/connect.html.erb
<h1>Oauth#connect</h1>
<p>Find me in app/views/oauth/connect.html.erb</p>

app/views/togs/_form.html.erb
<%= form_for(@tog) do |f| %>
  <% if @tog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tog.errors.count, "error") %> prohibited this tog from being saved:</h2>

      <ul>
      <% @tog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/togs/edit.html.erb
<h1>Editing tog</h1>

<%= render 'form' %>

<%= link_to 'Show', @tog %> |
<%= link_to 'Back', togs_path %>

app/views/togs/follows.html.erb
<h1>Listing togs</h1>

<a href="/oauth/connect">Connect with Instagram</a>'

app/views/togs/index.html.erb
<style>
		.map-wrap {
			width: 100%;
			height: 800px;
		}

		#map {
			width: 100%;
			height: 800px;
		}

</style>

<h1>IMAGEBRIEF INSTAGRAM FOLLOWING ON INSTAGRAM: </h1> 
	
	<div class="map-wrap">
	  <div id="map"></div>
	</div>

  <% for follow in @follows %>
    <% media = Instagram.user_recent_media(follow.id) %>
    <a href='https://instagram.com/#{follow.username}'/>
      <div style='margin: 5px; padding: 5px; display: inline-block'>
	      <% if media.first.location %>
	    		<span><%= media.first.location.longitude %></span>
	      	<span><%= media.first.location.latitude %></span>
	    	<% end %>
	      <p><%= follow.full_name %></p>
	      <img src='<%= follow.profile_picture %>'>
     	</div>
     </a>
   <% end %>

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

 <script>
 	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers(<%=raw @hash.to_json %>);
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	  markers = handler.addMarkers(<%=raw @hash.to_json %>);
 		console.log(markers);
	});
 </script>

app/views/togs/new.html.erb
<h1>New tog</h1>

<%= render 'form' %>

<%= link_to 'Back', togs_path %>

app/views/togs/show.html.erb
<h1> WHY SHOW </h1>

<%=  @client %>